version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:24.0  # Docker 실행 환경
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: apk add --no-cache openjdk17 gradle
      - run:
          name: Build the application
          command: ./gradlew clean build -x test
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build bootJar
          command: ./gradlew bootJar

  docker_build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t springboot-app:latest .
            docker images  # 빌드된 이미지 확인
      - run:
          name: Save Docker image as tar file
          command: |
            docker save -o springboot-app.tar springboot-app:latest
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache aws-cli
      - run:
          name: Upload Docker image to S3 (Private)
          command: |
            aws s3 cp springboot-app.tar s3://your-s3-bucket-name/docker-images/springboot-app.tar --acl private

  docker_run:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache aws-cli
      - run:
          name: Download Docker image from S3 (Private)
          command: |
            aws s3 cp s3://hanseungju/docker-images/springboot-app.tar springboot-app.tar
      - run:
          name: Load Docker image
          command: |
            docker load -i springboot-app.tar
      - run:
          name: Run Docker container
          command: |
            docker run -d -p 8080:8080 springboot-app:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
      - docker_run:
          requires:
            - docker_build