version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:24.0  # Docker가 포함된 환경
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: apk add --no-cache openjdk17 gradle
      - run:
          name: Build the application
          command: ./gradlew clean build -x test
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build bootJar
          command: ./gradlew bootJar

  docker_build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t springboot-app:latest .  # 이미지 빌드
            docker tag springboot-app:latest myrepo/springboot-app:latest  # 태그 추가 (확인용)
            docker images  # 빌드된 이미지 확인

  docker_run:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run Docker container
          command: |
            docker images  # 빌드된 이미지 확인
            docker run -d -p 8080:8080 springboot-app:latest || (echo "Image not found" && exit 1)
            sleep 10
            curl -f http://localhost:8080 || exit 1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
      - docker_run:
          requires:
            - docker_build