version: 2.1

executors:
  java-executor:
    docker:
      - image: openjdk:17-alpine  # Alpine 기반 이미지 사용
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install xargs (coreutils)
          command: apk update && apk add coreutils  # apk를 사용하여 coreutils 설치
      - run:
          name: Build the application
          command: ./gradlew clean build -x test
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build bootJar
          command: ./gradlew bootJar

  docker_build:
    executor: java-executor  # 추가된 executor
    docker:
      - image: openjdk:17-alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t springboot-app:latest .

  docker_run:
    executor: java-executor  # 추가된 executor
    docker:
      - image: openjdk:17-alpine
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Run Docker container
          command: |
            docker run -d -p 8080:8080 springboot-app:latest  # Docker 컨테이너 실행
            sleep 10  # 컨테이너가 시작할 때까지 대기
            curl -f http://localhost:8080 || exit 1  # 애플리케이션이 정상적으로 실행 중인지 확인

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
      - docker_run:
          requires:
            - docker_build