version: 2.1

executors:
  java-executor:
    docker:
      - image: openjdk:17-alpine
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apk update && apk add coreutils
      - run:
          name: Build the application
          command: ./gradlew clean build -x test
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build bootJar
          command: ./gradlew bootJar

  docker_build:
    executor: docker-executor
    docker:
      - image: docker:24.0  # 최신 Docker 이미지 사용
    steps:
      - checkout
      - setup_remote_docker:  # Docker 환경 설정
          docker_layer_caching: true
      - run:
          name: Install Docker CLI
          command: apk add --no-cache docker-cli
      - run:
          name: Build Docker image
          command: |
            docker build -t springboot-app:latest .

  docker_run:
    executor: docker-executor
    docker:
      - image: docker:24.0  # Docker 실행을 위한 환경
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run Docker container
          command: |
            docker run -d -p 8080:8080 springboot-app:latest
            sleep 10
            curl -f http://localhost:8080 || exit 1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
      - docker_run:
          requires:
            - docker_build