version: 2.1

executors:
  java-executor:
    docker:
      - image: openjdk:17-alpine  # Alpine 기반 이미지 사용
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install xargs (coreutils)
          command: apk update && apk add coreutils  # apk를 사용하여 coreutils 설치
      - run:
          name: Build the application
          command: ./gradlew clean build -x test
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build bootJar
          command: ./gradlew bootJar

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build